language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test -- -u
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 145ee577035562a0781d28a6406b7bbef2c9c7d1
  local_dir: build
  on:
    branch: master
